# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\lenovo\Desktop\qt\uwb-pyqt\ui\connect_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConnectionWidget(object):
    def setupUi(self, ConnectionWidget):
        ConnectionWidget.setObjectName("ConnectionWidget")
        ConnectionWidget.setEnabled(False)
        ConnectionWidget.resize(215, 40)
        ConnectionWidget.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label = QtWidgets.QLabel(ConnectionWidget)
        self.label.setGeometry(QtCore.QRect(9, 9, 24, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("")
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label.setObjectName("label")
        self.comPort = QtWidgets.QComboBox(ConnectionWidget)
        self.comPort.setGeometry(QtCore.QRect(39, 9, 100, 22))
        self.comPort.setMinimumSize(QtCore.QSize(100, 0))
        self.comPort.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.comPort.setObjectName("comPort")
        self.connect_pb = QtWidgets.QPushButton(ConnectionWidget)
        self.connect_pb.setGeometry(QtCore.QRect(145, 9, 80, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connect_pb.sizePolicy().hasHeightForWidth())
        self.connect_pb.setSizePolicy(sizePolicy)
        self.connect_pb.setMinimumSize(QtCore.QSize(50, 22))
        self.connect_pb.setStyleSheet("")
        self.connect_pb.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.connect_pb.setObjectName("connect_pb")

        self.retranslateUi(ConnectionWidget)
        QtCore.QMetaObject.connectSlotsByName(ConnectionWidget)

    def retranslateUi(self, ConnectionWidget):
        _translate = QtCore.QCoreApplication.translate
        ConnectionWidget.setWindowTitle(_translate("ConnectionWidget", "Form"))
        self.label.setText(_translate("ConnectionWidget", "串口"))
        self.connect_pb.setText(_translate("ConnectionWidget", "Connect"))
