# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\lenovo\Desktop\qt\uwb-pyqt\ui\graphics_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphicsWidget(object):
    def setupUi(self, GraphicsWidget):
        GraphicsWidget.setObjectName("GraphicsWidget")
        GraphicsWidget.resize(1002, 511)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GraphicsWidget.sizePolicy().hasHeightForWidth())
        GraphicsWidget.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(GraphicsWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.anchorTable = QtWidgets.QTableWidget(GraphicsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anchorTable.sizePolicy().hasHeightForWidth())
        self.anchorTable.setSizePolicy(sizePolicy)
        self.anchorTable.setMinimumSize(QtCore.QSize(0, 149))
        self.anchorTable.setMaximumSize(QtCore.QSize(535, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.anchorTable.setFont(font)
        self.anchorTable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.anchorTable.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.anchorTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.anchorTable.setAutoScroll(True)
        self.anchorTable.setAlternatingRowColors(True)
        self.anchorTable.setGridStyle(QtCore.Qt.SolidLine)
        self.anchorTable.setRowCount(8)
        self.anchorTable.setColumnCount(16)
        self.anchorTable.setObjectName("anchorTable")
        self.anchorTable.horizontalHeader().setDefaultSectionSize(20)
        self.anchorTable.horizontalHeader().setMinimumSectionSize(20)
        self.anchorTable.horizontalHeader().setStretchLastSection(False)
        self.anchorTable.verticalHeader().setVisible(False)
        self.anchorTable.verticalHeader().setDefaultSectionSize(18)
        self.anchorTable.verticalHeader().setHighlightSections(True)
        self.anchorTable.verticalHeader().setMinimumSectionSize(18)
        self.horizontalLayout.addWidget(self.anchorTable)
        self.tagTable = QtWidgets.QTableWidget(GraphicsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagTable.sizePolicy().hasHeightForWidth())
        self.tagTable.setSizePolicy(sizePolicy)
        self.tagTable.setMinimumSize(QtCore.QSize(0, 149))
        self.tagTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tagTable.setFont(font)
        self.tagTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tagTable.setAlternatingRowColors(True)
        self.tagTable.setRowCount(0)
        self.tagTable.setColumnCount(17)
        self.tagTable.setObjectName("tagTable")
        self.tagTable.horizontalHeader().setDefaultSectionSize(20)
        self.tagTable.horizontalHeader().setMinimumSectionSize(20)
        self.tagTable.horizontalHeader().setStretchLastSection(False)
        self.tagTable.verticalHeader().setVisible(False)
        self.tagTable.verticalHeader().setDefaultSectionSize(18)
        self.tagTable.verticalHeader().setMinimumSectionSize(18)
        self.horizontalLayout.addWidget(self.tagTable)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.graphicsView = GraphicsView(GraphicsWidget)
        self.graphicsView.setMaximumSize(QtCore.QSize(16777, 16777))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.stackedWidget = QtWidgets.QStackedWidget(GraphicsWidget)
        self.stackedWidget.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.stackedWidget.setObjectName("stackedWidget")
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(GraphicsWidget)
        self.stackedWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(GraphicsWidget)

    def retranslateUi(self, GraphicsWidget):
        _translate = QtCore.QCoreApplication.translate
        GraphicsWidget.setWindowTitle(_translate("GraphicsWidget", "Form"))
        self.anchorTable.setSortingEnabled(False)
from graphic_view import GraphicsView
