# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\lenovo\Desktop\qt\uwb-pyqt\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(775, 630)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/UWB.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.graphicsWidget = GraphicsWidget(MainWindow)
        self.graphicsWidget.setEnabled(True)
        self.graphicsWidget.setObjectName("graphicsWidget")
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 775, 22))
        self.menuBar.setObjectName("menuBar")
        self.viewMenu = QtWidgets.QMenu(self.menuBar)
        self.viewMenu.setObjectName("viewMenu")
        self.helpMenu = QtWidgets.QMenu(self.menuBar)
        self.helpMenu.setObjectName("helpMenu")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.minimap_dw = QtWidgets.QDockWidget(MainWindow)
        self.minimap_dw.setMinimumSize(QtCore.QSize(255, 39))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/haorutech.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimap_dw.setWindowIcon(icon1)
        self.minimap_dw.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.minimap_dw.setObjectName("minimap_dw")
        self.minimap = MinimapView()
        self.minimap.setObjectName("minimap")
        self.minimap_dw.setWidget(self.minimap)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.minimap_dw)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setMaximumSize(QtCore.QSize(16777215, 0))
        self.mainToolBar.setMovable(False)
        self.mainToolBar.setFloatable(False)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.viewSettings_dw = QtWidgets.QDockWidget(MainWindow)
        self.viewSettings_dw.setEnabled(True)
        self.viewSettings_dw.setMinimumSize(QtCore.QSize(260, 56))
        self.viewSettings_dw.setWindowIcon(icon1)
        self.viewSettings_dw.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.viewSettings_dw.setObjectName("viewSettings_dw")
        self.viewSettings_w = ViewSettingsWidget()
        self.viewSettings_w.setObjectName("viewSettings_w")
        self.viewSettings_dw.setWidget(self.viewSettings_w)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.viewSettings_dw)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionConfig = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/UWB.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfig.setIcon(icon2)
        self.actionConfig.setObjectName("actionConfig")
        self.actionLanguage = QtWidgets.QAction(MainWindow)
        self.actionLanguage.setObjectName("actionLanguage")
        self.action_cn = QtWidgets.QAction(MainWindow)
        self.action_cn.setObjectName("action_cn")
        self.action_en = QtWidgets.QAction(MainWindow)
        self.action_en.setObjectName("action_en")
        self.helpMenu.addAction(self.actionAbout)
        self.helpMenu.addAction(self.action_cn)
        self.helpMenu.addAction(self.action_en)
        self.menuBar.addAction(self.viewMenu.menuAction())
        self.menuBar.addAction(self.helpMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UWB科技HR-RTLS上位机"))
        self.viewMenu.setTitle(_translate("MainWindow", "显示"))
        self.helpMenu.setTitle(_translate("MainWindow", "帮助"))
        self.minimap_dw.setWindowTitle(_translate("MainWindow", "缩略底图"))
        self.viewSettings_dw.setWindowTitle(_translate("MainWindow", "参数设置"))
        self.actionAbout.setText(_translate("MainWindow", "关于UWB科技"))
        self.actionAbout.setToolTip(_translate("MainWindow", "关于UWB科技"))
        self.actionConfig.setText(_translate("MainWindow", "Channel Config"))
        self.actionLanguage.setText(_translate("MainWindow", "中/英文切换"))
        self.action_cn.setText(_translate("MainWindow", "中文"))
        self.action_en.setText(_translate("MainWindow", "英文"))
from MinimapView import MinimapView
from ViewSettingsWidget import ViewSettingsWidget
from graphics_widget.py import GraphicsWidget
import resources_rc
